### ISSUE TITLE
Utilizar Funções Não-Recursivas

### ISSUE THREAD

**Issue by GSimas** [GSimas/EEL7801#10]
Aprimorar código para o 3º protótipo, utilizando funções não-recursivas (como a MenuConfirm).
Usar alguma variável/argumento para verificar e retornar aos menus de seleção.

**Comment by GSimas** [comment]
Testar código compilado para o ATMEGA, de acordo com o commit [Aprimoramento do código (#10 e #11)](https://github.com/GSimas/EEL7801/commit/1b13209eb34c783bad1690a8d941d4b29feb4d10#diff-0d6378aba9780db510a9427354396a5bR135)

**Comment by andrempmattos** [comment]
Código validado após testes.
